name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, Test, and Analyze with SonarCloud
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create SonarCloud cache directories
        run: |
          mkdir -p ~/sonar/cache
          mkdir -p ./.sonar/scanner

      - name: Fetch latest SonarScanner version
        id: fetch_version
        run: |
          $response = Invoke-WebRequest -Uri 'https://api.github.com/repos/SonarSource/sonar-scanner-msbuild/releases/latest'
          $json = $response.Content | ConvertFrom-Json
          $version = $json.tag_name -replace 'v', ''
          echo "Latest SonarScanner version is $version"
          echo "##vso[task.setvariable variable=latest_version]$version"

      - name: Download and extract SonarScanner
        run: |
          $version = '${{ steps.fetch_version.outputs.latest_version }}'
          $url = "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$version.zip"
          Invoke-WebRequest -Uri $url -OutFile 'sonar-scanner.zip'
          Expand-Archive -Path 'sonar-scanner.zip' -DestinationPath '.\sonar-scanner'
          Remove-Item 'sonar-scanner.zip'

      - name: Set SonarScanner path
        run: |
          $env:PATH = "$env:PATH;$(Get-Location)\sonar-scanner\bin"

      - name: Run SonarScanner
        run: |
          ./sonar-scanner begin /k:"SamRoden22_MemberAdministrationLedub" /o:"samroden22" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.projectKey="SamRoden22_MemberAdministrationLedub" /d:sonar.organization="samroden22"
        shell: pwsh
        env:
          JAVA_HOME: C:\hostedtoolcache\windows\Java_Zulu_jdk\17.0.11-9\x64
          JAVA_HOME_17_X64: C:\hostedtoolcache\windows\Java_Zulu_jdk\17.0.11-9\x64
