name: .NET Core CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
    - uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Run StyleCop
      run: dotnet build /p:StyleCopEnabled=true

    - name: Run Roslyn Analyzers
      run: dotnet build /p:RunAnalyzers=true

  sonarcloud-analysis:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet sonarscanner begin /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.organization=samroden22 /d:sonar.projectKey=sonar.pullrequest.provider /d:sonar.host.url=https://sonarcloud.io
        dotnet build
        dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
